version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
      - "4444:4444"
    volumes:
      - ./failed_results.json:./failed_results.json
      - ./encodings:./encodings
    command: ["python", "manage.py", "runserver"]
    restart: always

